// Mocks generated by Mockito 5.4.5 from annotations
// in cocolab_messaging/test/services/profile_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i11;
import 'dart:io' as _i7;
import 'dart:typed_data' as _i10;

import 'package:firebase_core/firebase_core.dart' as _i3;
import 'package:firebase_database/firebase_database.dart' as _i2;
import 'package:firebase_database_platform_interface/firebase_database_platform_interface.dart'
    as _i9;
import 'package:firebase_storage/firebase_storage.dart' as _i4;
import 'package:firebase_storage_platform_interface/firebase_storage_platform_interface.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabaseReference_0 extends _i1.SmartFake
    implements _i2.DatabaseReference {
  _FakeDatabaseReference_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionResult_1 extends _i1.SmartFake
    implements _i2.TransactionResult {
  _FakeTransactionResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOnDisconnect_2 extends _i1.SmartFake implements _i2.OnDisconnect {
  _FakeOnDisconnect_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDataSnapshot_3 extends _i1.SmartFake implements _i2.DataSnapshot {
  _FakeDataSnapshot_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseEvent_4 extends _i1.SmartFake implements _i2.DatabaseEvent {
  _FakeDatabaseEvent_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuery_5 extends _i1.SmartFake implements _i2.Query {
  _FakeQuery_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_6 extends _i1.SmartFake implements _i3.FirebaseApp {
  _FakeFirebaseApp_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_7 extends _i1.SmartFake implements Duration {
  _FakeDuration_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReference_8 extends _i1.SmartFake implements _i4.Reference {
  _FakeReference_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseStorage_9 extends _i1.SmartFake
    implements _i4.FirebaseStorage {
  _FakeFirebaseStorage_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFullMetadata_10 extends _i1.SmartFake implements _i5.FullMetadata {
  _FakeFullMetadata_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListResult_11 extends _i1.SmartFake implements _i4.ListResult {
  _FakeListResult_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadTask_12 extends _i1.SmartFake implements _i4.UploadTask {
  _FakeUploadTask_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDownloadTask_13 extends _i1.SmartFake implements _i4.DownloadTask {
  _FakeDownloadTask_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskSnapshot_14 extends _i1.SmartFake implements _i4.TaskSnapshot {
  _FakeTaskSnapshot_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_15<T> extends _i1.SmartFake implements _i6.Future<T> {
  _FakeFuture_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_16 extends _i1.SmartFake implements _i7.File {
  _FakeFile_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_17 extends _i1.SmartFake implements Uri {
  _FakeUri_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectory_18 extends _i1.SmartFake implements _i7.Directory {
  _FakeDirectory_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileSystemEntity_19 extends _i1.SmartFake
    implements _i7.FileSystemEntity {
  _FakeFileSystemEntity_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_20 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRandomAccessFile_21 extends _i1.SmartFake
    implements _i7.RandomAccessFile {
  _FakeRandomAccessFile_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSink_22 extends _i1.SmartFake implements _i7.IOSink {
  _FakeIOSink_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileStat_23 extends _i1.SmartFake implements _i7.FileStat {
  _FakeFileStat_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseReference].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseReference extends _i1.Mock implements _i2.DatabaseReference {
  @override
  _i2.DatabaseReference get root =>
      (super.noSuchMethod(
            Invocation.getter(#root),
            returnValue: _FakeDatabaseReference_0(
              this,
              Invocation.getter(#root),
            ),
            returnValueForMissingStub: _FakeDatabaseReference_0(
              this,
              Invocation.getter(#root),
            ),
          )
          as _i2.DatabaseReference);

  @override
  _i2.DatabaseReference get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeDatabaseReference_0(
              this,
              Invocation.getter(#ref),
            ),
            returnValueForMissingStub: _FakeDatabaseReference_0(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i2.DatabaseReference);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#path)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  _i6.Stream<_i2.DatabaseEvent> get onChildAdded =>
      (super.noSuchMethod(
            Invocation.getter(#onChildAdded),
            returnValue: _i6.Stream<_i2.DatabaseEvent>.empty(),
            returnValueForMissingStub: _i6.Stream<_i2.DatabaseEvent>.empty(),
          )
          as _i6.Stream<_i2.DatabaseEvent>);

  @override
  _i6.Stream<_i2.DatabaseEvent> get onChildRemoved =>
      (super.noSuchMethod(
            Invocation.getter(#onChildRemoved),
            returnValue: _i6.Stream<_i2.DatabaseEvent>.empty(),
            returnValueForMissingStub: _i6.Stream<_i2.DatabaseEvent>.empty(),
          )
          as _i6.Stream<_i2.DatabaseEvent>);

  @override
  _i6.Stream<_i2.DatabaseEvent> get onChildChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onChildChanged),
            returnValue: _i6.Stream<_i2.DatabaseEvent>.empty(),
            returnValueForMissingStub: _i6.Stream<_i2.DatabaseEvent>.empty(),
          )
          as _i6.Stream<_i2.DatabaseEvent>);

  @override
  _i6.Stream<_i2.DatabaseEvent> get onChildMoved =>
      (super.noSuchMethod(
            Invocation.getter(#onChildMoved),
            returnValue: _i6.Stream<_i2.DatabaseEvent>.empty(),
            returnValueForMissingStub: _i6.Stream<_i2.DatabaseEvent>.empty(),
          )
          as _i6.Stream<_i2.DatabaseEvent>);

  @override
  _i6.Stream<_i2.DatabaseEvent> get onValue =>
      (super.noSuchMethod(
            Invocation.getter(#onValue),
            returnValue: _i6.Stream<_i2.DatabaseEvent>.empty(),
            returnValueForMissingStub: _i6.Stream<_i2.DatabaseEvent>.empty(),
          )
          as _i6.Stream<_i2.DatabaseEvent>);

  @override
  _i2.DatabaseReference child(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#child, [path]),
            returnValue: _FakeDatabaseReference_0(
              this,
              Invocation.method(#child, [path]),
            ),
            returnValueForMissingStub: _FakeDatabaseReference_0(
              this,
              Invocation.method(#child, [path]),
            ),
          )
          as _i2.DatabaseReference);

  @override
  _i2.DatabaseReference push() =>
      (super.noSuchMethod(
            Invocation.method(#push, []),
            returnValue: _FakeDatabaseReference_0(
              this,
              Invocation.method(#push, []),
            ),
            returnValueForMissingStub: _FakeDatabaseReference_0(
              this,
              Invocation.method(#push, []),
            ),
          )
          as _i2.DatabaseReference);

  @override
  _i6.Future<void> set(Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#set, [value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setWithPriority(Object? value, Object? priority) =>
      (super.noSuchMethod(
            Invocation.method(#setWithPriority, [value, priority]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> update(Map<String, Object?>? value) =>
      (super.noSuchMethod(
            Invocation.method(#update, [value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setPriority(Object? priority) =>
      (super.noSuchMethod(
            Invocation.method(#setPriority, [priority]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> remove() =>
      (super.noSuchMethod(
            Invocation.method(#remove, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.TransactionResult> runTransaction(
    _i9.TransactionHandler? transactionHandler, {
    bool? applyLocally = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runTransaction,
              [transactionHandler],
              {#applyLocally: applyLocally},
            ),
            returnValue: _i6.Future<_i2.TransactionResult>.value(
              _FakeTransactionResult_1(
                this,
                Invocation.method(
                  #runTransaction,
                  [transactionHandler],
                  {#applyLocally: applyLocally},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.TransactionResult>.value(
              _FakeTransactionResult_1(
                this,
                Invocation.method(
                  #runTransaction,
                  [transactionHandler],
                  {#applyLocally: applyLocally},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.TransactionResult>);

  @override
  _i2.OnDisconnect onDisconnect() =>
      (super.noSuchMethod(
            Invocation.method(#onDisconnect, []),
            returnValue: _FakeOnDisconnect_2(
              this,
              Invocation.method(#onDisconnect, []),
            ),
            returnValueForMissingStub: _FakeOnDisconnect_2(
              this,
              Invocation.method(#onDisconnect, []),
            ),
          )
          as _i2.OnDisconnect);

  @override
  _i6.Future<_i2.DataSnapshot> get() =>
      (super.noSuchMethod(
            Invocation.method(#get, []),
            returnValue: _i6.Future<_i2.DataSnapshot>.value(
              _FakeDataSnapshot_3(this, Invocation.method(#get, [])),
            ),
            returnValueForMissingStub: _i6.Future<_i2.DataSnapshot>.value(
              _FakeDataSnapshot_3(this, Invocation.method(#get, [])),
            ),
          )
          as _i6.Future<_i2.DataSnapshot>);

  @override
  _i6.Future<_i2.DatabaseEvent> once([
    _i9.DatabaseEventType? eventType = _i9.DatabaseEventType.value,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#once, [eventType]),
            returnValue: _i6.Future<_i2.DatabaseEvent>.value(
              _FakeDatabaseEvent_4(this, Invocation.method(#once, [eventType])),
            ),
            returnValueForMissingStub: _i6.Future<_i2.DatabaseEvent>.value(
              _FakeDatabaseEvent_4(this, Invocation.method(#once, [eventType])),
            ),
          )
          as _i6.Future<_i2.DatabaseEvent>);

  @override
  _i2.Query startAt(Object? value, {String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#startAt, [value], {#key: key}),
            returnValue: _FakeQuery_5(
              this,
              Invocation.method(#startAt, [value], {#key: key}),
            ),
            returnValueForMissingStub: _FakeQuery_5(
              this,
              Invocation.method(#startAt, [value], {#key: key}),
            ),
          )
          as _i2.Query);

  @override
  _i2.Query startAfter(Object? value, {String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#startAfter, [value], {#key: key}),
            returnValue: _FakeQuery_5(
              this,
              Invocation.method(#startAfter, [value], {#key: key}),
            ),
            returnValueForMissingStub: _FakeQuery_5(
              this,
              Invocation.method(#startAfter, [value], {#key: key}),
            ),
          )
          as _i2.Query);

  @override
  _i2.Query endAt(Object? value, {String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#endAt, [value], {#key: key}),
            returnValue: _FakeQuery_5(
              this,
              Invocation.method(#endAt, [value], {#key: key}),
            ),
            returnValueForMissingStub: _FakeQuery_5(
              this,
              Invocation.method(#endAt, [value], {#key: key}),
            ),
          )
          as _i2.Query);

  @override
  _i2.Query endBefore(Object? value, {String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#endBefore, [value], {#key: key}),
            returnValue: _FakeQuery_5(
              this,
              Invocation.method(#endBefore, [value], {#key: key}),
            ),
            returnValueForMissingStub: _FakeQuery_5(
              this,
              Invocation.method(#endBefore, [value], {#key: key}),
            ),
          )
          as _i2.Query);

  @override
  _i2.Query equalTo(Object? value, {String? key}) =>
      (super.noSuchMethod(
            Invocation.method(#equalTo, [value], {#key: key}),
            returnValue: _FakeQuery_5(
              this,
              Invocation.method(#equalTo, [value], {#key: key}),
            ),
            returnValueForMissingStub: _FakeQuery_5(
              this,
              Invocation.method(#equalTo, [value], {#key: key}),
            ),
          )
          as _i2.Query);

  @override
  _i2.Query limitToFirst(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#limitToFirst, [limit]),
            returnValue: _FakeQuery_5(
              this,
              Invocation.method(#limitToFirst, [limit]),
            ),
            returnValueForMissingStub: _FakeQuery_5(
              this,
              Invocation.method(#limitToFirst, [limit]),
            ),
          )
          as _i2.Query);

  @override
  _i2.Query limitToLast(int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#limitToLast, [limit]),
            returnValue: _FakeQuery_5(
              this,
              Invocation.method(#limitToLast, [limit]),
            ),
            returnValueForMissingStub: _FakeQuery_5(
              this,
              Invocation.method(#limitToLast, [limit]),
            ),
          )
          as _i2.Query);

  @override
  _i2.Query orderByChild(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#orderByChild, [path]),
            returnValue: _FakeQuery_5(
              this,
              Invocation.method(#orderByChild, [path]),
            ),
            returnValueForMissingStub: _FakeQuery_5(
              this,
              Invocation.method(#orderByChild, [path]),
            ),
          )
          as _i2.Query);

  @override
  _i2.Query orderByKey() =>
      (super.noSuchMethod(
            Invocation.method(#orderByKey, []),
            returnValue: _FakeQuery_5(this, Invocation.method(#orderByKey, [])),
            returnValueForMissingStub: _FakeQuery_5(
              this,
              Invocation.method(#orderByKey, []),
            ),
          )
          as _i2.Query);

  @override
  _i2.Query orderByValue() =>
      (super.noSuchMethod(
            Invocation.method(#orderByValue, []),
            returnValue: _FakeQuery_5(
              this,
              Invocation.method(#orderByValue, []),
            ),
            returnValueForMissingStub: _FakeQuery_5(
              this,
              Invocation.method(#orderByValue, []),
            ),
          )
          as _i2.Query);

  @override
  _i2.Query orderByPriority() =>
      (super.noSuchMethod(
            Invocation.method(#orderByPriority, []),
            returnValue: _FakeQuery_5(
              this,
              Invocation.method(#orderByPriority, []),
            ),
            returnValueForMissingStub: _FakeQuery_5(
              this,
              Invocation.method(#orderByPriority, []),
            ),
          )
          as _i2.Query);

  @override
  _i6.Future<void> keepSynced(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#keepSynced, [value]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [DataSnapshot].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataSnapshot extends _i1.Mock implements _i2.DataSnapshot {
  @override
  _i2.DatabaseReference get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeDatabaseReference_0(
              this,
              Invocation.getter(#ref),
            ),
            returnValueForMissingStub: _FakeDatabaseReference_0(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i2.DatabaseReference);

  @override
  bool get exists =>
      (super.noSuchMethod(
            Invocation.getter(#exists),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Iterable<_i2.DataSnapshot> get children =>
      (super.noSuchMethod(
            Invocation.getter(#children),
            returnValue: <_i2.DataSnapshot>[],
            returnValueForMissingStub: <_i2.DataSnapshot>[],
          )
          as Iterable<_i2.DataSnapshot>);

  @override
  bool hasChild(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#hasChild, [path]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.DataSnapshot child(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#child, [path]),
            returnValue: _FakeDataSnapshot_3(
              this,
              Invocation.method(#child, [path]),
            ),
            returnValueForMissingStub: _FakeDataSnapshot_3(
              this,
              Invocation.method(#child, [path]),
            ),
          )
          as _i2.DataSnapshot);
}

/// A class which mocks [FirebaseStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseStorage extends _i1.Mock implements _i4.FirebaseStorage {
  @override
  _i3.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_6(this, Invocation.getter(#app)),
            returnValueForMissingStub: _FakeFirebaseApp_6(
              this,
              Invocation.getter(#app),
            ),
          )
          as _i3.FirebaseApp);

  @override
  set app(_i3.FirebaseApp? _app) => super.noSuchMethod(
    Invocation.setter(#app, _app),
    returnValueForMissingStub: null,
  );

  @override
  String get bucket =>
      (super.noSuchMethod(
            Invocation.getter(#bucket),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#bucket),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#bucket),
            ),
          )
          as String);

  @override
  set bucket(String? _bucket) => super.noSuchMethod(
    Invocation.setter(#bucket, _bucket),
    returnValueForMissingStub: null,
  );

  @override
  Duration get maxOperationRetryTime =>
      (super.noSuchMethod(
            Invocation.getter(#maxOperationRetryTime),
            returnValue: _FakeDuration_7(
              this,
              Invocation.getter(#maxOperationRetryTime),
            ),
            returnValueForMissingStub: _FakeDuration_7(
              this,
              Invocation.getter(#maxOperationRetryTime),
            ),
          )
          as Duration);

  @override
  Duration get maxUploadRetryTime =>
      (super.noSuchMethod(
            Invocation.getter(#maxUploadRetryTime),
            returnValue: _FakeDuration_7(
              this,
              Invocation.getter(#maxUploadRetryTime),
            ),
            returnValueForMissingStub: _FakeDuration_7(
              this,
              Invocation.getter(#maxUploadRetryTime),
            ),
          )
          as Duration);

  @override
  Duration get maxDownloadRetryTime =>
      (super.noSuchMethod(
            Invocation.getter(#maxDownloadRetryTime),
            returnValue: _FakeDuration_7(
              this,
              Invocation.getter(#maxDownloadRetryTime),
            ),
            returnValueForMissingStub: _FakeDuration_7(
              this,
              Invocation.getter(#maxDownloadRetryTime),
            ),
          )
          as Duration);

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
            returnValueForMissingStub: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i4.Reference ref([String? path]) =>
      (super.noSuchMethod(
            Invocation.method(#ref, [path]),
            returnValue: _FakeReference_8(
              this,
              Invocation.method(#ref, [path]),
            ),
            returnValueForMissingStub: _FakeReference_8(
              this,
              Invocation.method(#ref, [path]),
            ),
          )
          as _i4.Reference);

  @override
  _i4.Reference refFromURL(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#refFromURL, [url]),
            returnValue: _FakeReference_8(
              this,
              Invocation.method(#refFromURL, [url]),
            ),
            returnValueForMissingStub: _FakeReference_8(
              this,
              Invocation.method(#refFromURL, [url]),
            ),
          )
          as _i4.Reference);

  @override
  void setMaxOperationRetryTime(Duration? time) => super.noSuchMethod(
    Invocation.method(#setMaxOperationRetryTime, [time]),
    returnValueForMissingStub: null,
  );

  @override
  void setMaxUploadRetryTime(Duration? time) => super.noSuchMethod(
    Invocation.method(#setMaxUploadRetryTime, [time]),
    returnValueForMissingStub: null,
  );

  @override
  void setMaxDownloadRetryTime(Duration? time) => super.noSuchMethod(
    Invocation.method(#setMaxDownloadRetryTime, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> useStorageEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #useStorageEmulator,
              [host, port],
              {#automaticHostMapping: automaticHostMapping},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [Reference].
///
/// See the documentation for Mockito's code generation for more information.
class MockReference extends _i1.Mock implements _i4.Reference {
  @override
  _i4.FirebaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeFirebaseStorage_9(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeFirebaseStorage_9(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i4.FirebaseStorage);

  @override
  String get bucket =>
      (super.noSuchMethod(
            Invocation.getter(#bucket),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#bucket),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#bucket),
            ),
          )
          as String);

  @override
  String get fullPath =>
      (super.noSuchMethod(
            Invocation.getter(#fullPath),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#fullPath),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#fullPath),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  _i4.Reference get root =>
      (super.noSuchMethod(
            Invocation.getter(#root),
            returnValue: _FakeReference_8(this, Invocation.getter(#root)),
            returnValueForMissingStub: _FakeReference_8(
              this,
              Invocation.getter(#root),
            ),
          )
          as _i4.Reference);

  @override
  _i4.Reference child(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#child, [path]),
            returnValue: _FakeReference_8(
              this,
              Invocation.method(#child, [path]),
            ),
            returnValueForMissingStub: _FakeReference_8(
              this,
              Invocation.method(#child, [path]),
            ),
          )
          as _i4.Reference);

  @override
  _i6.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> getDownloadURL() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadURL, []),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getDownloadURL, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getDownloadURL, []),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i5.FullMetadata> getMetadata() =>
      (super.noSuchMethod(
            Invocation.method(#getMetadata, []),
            returnValue: _i6.Future<_i5.FullMetadata>.value(
              _FakeFullMetadata_10(this, Invocation.method(#getMetadata, [])),
            ),
            returnValueForMissingStub: _i6.Future<_i5.FullMetadata>.value(
              _FakeFullMetadata_10(this, Invocation.method(#getMetadata, [])),
            ),
          )
          as _i6.Future<_i5.FullMetadata>);

  @override
  _i6.Future<_i4.ListResult> list([_i5.ListOptions? options]) =>
      (super.noSuchMethod(
            Invocation.method(#list, [options]),
            returnValue: _i6.Future<_i4.ListResult>.value(
              _FakeListResult_11(this, Invocation.method(#list, [options])),
            ),
            returnValueForMissingStub: _i6.Future<_i4.ListResult>.value(
              _FakeListResult_11(this, Invocation.method(#list, [options])),
            ),
          )
          as _i6.Future<_i4.ListResult>);

  @override
  _i6.Future<_i4.ListResult> listAll() =>
      (super.noSuchMethod(
            Invocation.method(#listAll, []),
            returnValue: _i6.Future<_i4.ListResult>.value(
              _FakeListResult_11(this, Invocation.method(#listAll, [])),
            ),
            returnValueForMissingStub: _i6.Future<_i4.ListResult>.value(
              _FakeListResult_11(this, Invocation.method(#listAll, [])),
            ),
          )
          as _i6.Future<_i4.ListResult>);

  @override
  _i6.Future<_i10.Uint8List?> getData([int? maxSize = 10485760]) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [maxSize]),
            returnValue: _i6.Future<_i10.Uint8List?>.value(),
            returnValueForMissingStub: _i6.Future<_i10.Uint8List?>.value(),
          )
          as _i6.Future<_i10.Uint8List?>);

  @override
  _i4.UploadTask putData(
    _i10.Uint8List? data, [
    _i5.SettableMetadata? metadata,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#putData, [data, metadata]),
            returnValue: _FakeUploadTask_12(
              this,
              Invocation.method(#putData, [data, metadata]),
            ),
            returnValueForMissingStub: _FakeUploadTask_12(
              this,
              Invocation.method(#putData, [data, metadata]),
            ),
          )
          as _i4.UploadTask);

  @override
  _i4.UploadTask putBlob(dynamic blob, [_i5.SettableMetadata? metadata]) =>
      (super.noSuchMethod(
            Invocation.method(#putBlob, [blob, metadata]),
            returnValue: _FakeUploadTask_12(
              this,
              Invocation.method(#putBlob, [blob, metadata]),
            ),
            returnValueForMissingStub: _FakeUploadTask_12(
              this,
              Invocation.method(#putBlob, [blob, metadata]),
            ),
          )
          as _i4.UploadTask);

  @override
  _i4.UploadTask putFile(_i7.File? file, [_i5.SettableMetadata? metadata]) =>
      (super.noSuchMethod(
            Invocation.method(#putFile, [file, metadata]),
            returnValue: _FakeUploadTask_12(
              this,
              Invocation.method(#putFile, [file, metadata]),
            ),
            returnValueForMissingStub: _FakeUploadTask_12(
              this,
              Invocation.method(#putFile, [file, metadata]),
            ),
          )
          as _i4.UploadTask);

  @override
  _i4.UploadTask putString(
    String? data, {
    _i5.PutStringFormat? format = _i5.PutStringFormat.raw,
    _i5.SettableMetadata? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putString,
              [data],
              {#format: format, #metadata: metadata},
            ),
            returnValue: _FakeUploadTask_12(
              this,
              Invocation.method(
                #putString,
                [data],
                {#format: format, #metadata: metadata},
              ),
            ),
            returnValueForMissingStub: _FakeUploadTask_12(
              this,
              Invocation.method(
                #putString,
                [data],
                {#format: format, #metadata: metadata},
              ),
            ),
          )
          as _i4.UploadTask);

  @override
  _i6.Future<_i5.FullMetadata> updateMetadata(_i5.SettableMetadata? metadata) =>
      (super.noSuchMethod(
            Invocation.method(#updateMetadata, [metadata]),
            returnValue: _i6.Future<_i5.FullMetadata>.value(
              _FakeFullMetadata_10(
                this,
                Invocation.method(#updateMetadata, [metadata]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i5.FullMetadata>.value(
              _FakeFullMetadata_10(
                this,
                Invocation.method(#updateMetadata, [metadata]),
              ),
            ),
          )
          as _i6.Future<_i5.FullMetadata>);

  @override
  _i4.DownloadTask writeToFile(_i7.File? file) =>
      (super.noSuchMethod(
            Invocation.method(#writeToFile, [file]),
            returnValue: _FakeDownloadTask_13(
              this,
              Invocation.method(#writeToFile, [file]),
            ),
            returnValueForMissingStub: _FakeDownloadTask_13(
              this,
              Invocation.method(#writeToFile, [file]),
            ),
          )
          as _i4.DownloadTask);
}

/// A class which mocks [UploadTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadTask extends _i1.Mock implements _i4.UploadTask {
  @override
  _i4.FirebaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeFirebaseStorage_9(
              this,
              Invocation.getter(#storage),
            ),
            returnValueForMissingStub: _FakeFirebaseStorage_9(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i4.FirebaseStorage);

  @override
  _i6.Stream<_i4.TaskSnapshot> get snapshotEvents =>
      (super.noSuchMethod(
            Invocation.getter(#snapshotEvents),
            returnValue: _i6.Stream<_i4.TaskSnapshot>.empty(),
            returnValueForMissingStub: _i6.Stream<_i4.TaskSnapshot>.empty(),
          )
          as _i6.Stream<_i4.TaskSnapshot>);

  @override
  _i4.TaskSnapshot get snapshot =>
      (super.noSuchMethod(
            Invocation.getter(#snapshot),
            returnValue: _FakeTaskSnapshot_14(
              this,
              Invocation.getter(#snapshot),
            ),
            returnValueForMissingStub: _FakeTaskSnapshot_14(
              this,
              Invocation.getter(#snapshot),
            ),
          )
          as _i4.TaskSnapshot);

  @override
  _i6.Future<bool> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> cancel() =>
      (super.noSuchMethod(
            Invocation.method(#cancel, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Stream<_i4.TaskSnapshot> asStream() =>
      (super.noSuchMethod(
            Invocation.method(#asStream, []),
            returnValue: _i6.Stream<_i4.TaskSnapshot>.empty(),
            returnValueForMissingStub: _i6.Stream<_i4.TaskSnapshot>.empty(),
          )
          as _i6.Stream<_i4.TaskSnapshot>);

  @override
  _i6.Future<_i4.TaskSnapshot> catchError(
    Function? onError, {
    bool Function(Object)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#catchError, [onError], {#test: test}),
            returnValue: _i6.Future<_i4.TaskSnapshot>.value(
              _FakeTaskSnapshot_14(
                this,
                Invocation.method(#catchError, [onError], {#test: test}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.TaskSnapshot>.value(
              _FakeTaskSnapshot_14(
                this,
                Invocation.method(#catchError, [onError], {#test: test}),
              ),
            ),
          )
          as _i6.Future<_i4.TaskSnapshot>);

  @override
  _i6.Future<S> then<S>(
    _i6.FutureOr<S> Function(_i4.TaskSnapshot)? onValue, {
    Function? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#then, [onValue], {#onError: onError}),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<S>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (S v) => _i6.Future<S>.value(v),
                ) ??
                _FakeFuture_15<S>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
            returnValueForMissingStub:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<S>(
                    this,
                    Invocation.method(#then, [onValue], {#onError: onError}),
                  ),
                  (S v) => _i6.Future<S>.value(v),
                ) ??
                _FakeFuture_15<S>(
                  this,
                  Invocation.method(#then, [onValue], {#onError: onError}),
                ),
          )
          as _i6.Future<S>);

  @override
  _i6.Future<_i4.TaskSnapshot> whenComplete(
    _i6.FutureOr<dynamic> Function()? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#whenComplete, [action]),
            returnValue: _i6.Future<_i4.TaskSnapshot>.value(
              _FakeTaskSnapshot_14(
                this,
                Invocation.method(#whenComplete, [action]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.TaskSnapshot>.value(
              _FakeTaskSnapshot_14(
                this,
                Invocation.method(#whenComplete, [action]),
              ),
            ),
          )
          as _i6.Future<_i4.TaskSnapshot>);

  @override
  _i6.Future<_i4.TaskSnapshot> timeout(
    Duration? timeLimit, {
    _i6.FutureOr<_i4.TaskSnapshot> Function()? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue: _i6.Future<_i4.TaskSnapshot>.value(
              _FakeTaskSnapshot_14(
                this,
                Invocation.method(
                  #timeout,
                  [timeLimit],
                  {#onTimeout: onTimeout},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.TaskSnapshot>.value(
              _FakeTaskSnapshot_14(
                this,
                Invocation.method(
                  #timeout,
                  [timeLimit],
                  {#onTimeout: onTimeout},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.TaskSnapshot>);
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i7.File {
  @override
  _i7.File get absolute =>
      (super.noSuchMethod(
            Invocation.getter(#absolute),
            returnValue: _FakeFile_16(this, Invocation.getter(#absolute)),
            returnValueForMissingStub: _FakeFile_16(
              this,
              Invocation.getter(#absolute),
            ),
          )
          as _i7.File);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#path)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  Uri get uri =>
      (super.noSuchMethod(
            Invocation.getter(#uri),
            returnValue: _FakeUri_17(this, Invocation.getter(#uri)),
            returnValueForMissingStub: _FakeUri_17(
              this,
              Invocation.getter(#uri),
            ),
          )
          as Uri);

  @override
  bool get isAbsolute =>
      (super.noSuchMethod(
            Invocation.getter(#isAbsolute),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Directory get parent =>
      (super.noSuchMethod(
            Invocation.getter(#parent),
            returnValue: _FakeDirectory_18(this, Invocation.getter(#parent)),
            returnValueForMissingStub: _FakeDirectory_18(
              this,
              Invocation.getter(#parent),
            ),
          )
          as _i7.Directory);

  @override
  _i6.Future<_i7.File> create({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #recursive: recursive,
              #exclusive: exclusive,
            }),
            returnValue: _i6.Future<_i7.File>.value(
              _FakeFile_16(
                this,
                Invocation.method(#create, [], {
                  #recursive: recursive,
                  #exclusive: exclusive,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.File>.value(
              _FakeFile_16(
                this,
                Invocation.method(#create, [], {
                  #recursive: recursive,
                  #exclusive: exclusive,
                }),
              ),
            ),
          )
          as _i6.Future<_i7.File>);

  @override
  void createSync({bool? recursive = false, bool? exclusive = false}) =>
      super.noSuchMethod(
        Invocation.method(#createSync, [], {
          #recursive: recursive,
          #exclusive: exclusive,
        }),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i7.File> rename(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#rename, [newPath]),
            returnValue: _i6.Future<_i7.File>.value(
              _FakeFile_16(this, Invocation.method(#rename, [newPath])),
            ),
            returnValueForMissingStub: _i6.Future<_i7.File>.value(
              _FakeFile_16(this, Invocation.method(#rename, [newPath])),
            ),
          )
          as _i6.Future<_i7.File>);

  @override
  _i7.File renameSync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#renameSync, [newPath]),
            returnValue: _FakeFile_16(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
            returnValueForMissingStub: _FakeFile_16(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
          )
          as _i7.File);

  @override
  _i6.Future<_i7.FileSystemEntity> delete({bool? recursive = false}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#recursive: recursive}),
            returnValue: _i6.Future<_i7.FileSystemEntity>.value(
              _FakeFileSystemEntity_19(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.FileSystemEntity>.value(
              _FakeFileSystemEntity_19(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
          )
          as _i6.Future<_i7.FileSystemEntity>);

  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
    Invocation.method(#deleteSync, [], {#recursive: recursive}),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i7.File> copy(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copy, [newPath]),
            returnValue: _i6.Future<_i7.File>.value(
              _FakeFile_16(this, Invocation.method(#copy, [newPath])),
            ),
            returnValueForMissingStub: _i6.Future<_i7.File>.value(
              _FakeFile_16(this, Invocation.method(#copy, [newPath])),
            ),
          )
          as _i6.Future<_i7.File>);

  @override
  _i7.File copySync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copySync, [newPath]),
            returnValue: _FakeFile_16(
              this,
              Invocation.method(#copySync, [newPath]),
            ),
            returnValueForMissingStub: _FakeFile_16(
              this,
              Invocation.method(#copySync, [newPath]),
            ),
          )
          as _i7.File);

  @override
  _i6.Future<int> length() =>
      (super.noSuchMethod(
            Invocation.method(#length, []),
            returnValue: _i6.Future<int>.value(0),
            returnValueForMissingStub: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  int lengthSync() =>
      (super.noSuchMethod(
            Invocation.method(#lengthSync, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i6.Future<DateTime> lastAccessed() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessed, []),
            returnValue: _i6.Future<DateTime>.value(
              _FakeDateTime_20(this, Invocation.method(#lastAccessed, [])),
            ),
            returnValueForMissingStub: _i6.Future<DateTime>.value(
              _FakeDateTime_20(this, Invocation.method(#lastAccessed, [])),
            ),
          )
          as _i6.Future<DateTime>);

  @override
  DateTime lastAccessedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessedSync, []),
            returnValue: _FakeDateTime_20(
              this,
              Invocation.method(#lastAccessedSync, []),
            ),
            returnValueForMissingStub: _FakeDateTime_20(
              this,
              Invocation.method(#lastAccessedSync, []),
            ),
          )
          as DateTime);

  @override
  _i6.Future<dynamic> setLastAccessed(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastAccessed, [time]),
            returnValue: _i6.Future<dynamic>.value(),
            returnValueForMissingStub: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  void setLastAccessedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastAccessedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<DateTime> lastModified() =>
      (super.noSuchMethod(
            Invocation.method(#lastModified, []),
            returnValue: _i6.Future<DateTime>.value(
              _FakeDateTime_20(this, Invocation.method(#lastModified, [])),
            ),
            returnValueForMissingStub: _i6.Future<DateTime>.value(
              _FakeDateTime_20(this, Invocation.method(#lastModified, [])),
            ),
          )
          as _i6.Future<DateTime>);

  @override
  DateTime lastModifiedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastModifiedSync, []),
            returnValue: _FakeDateTime_20(
              this,
              Invocation.method(#lastModifiedSync, []),
            ),
            returnValueForMissingStub: _FakeDateTime_20(
              this,
              Invocation.method(#lastModifiedSync, []),
            ),
          )
          as DateTime);

  @override
  _i6.Future<dynamic> setLastModified(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastModified, [time]),
            returnValue: _i6.Future<dynamic>.value(),
            returnValueForMissingStub: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  void setLastModifiedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastModifiedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i7.RandomAccessFile> open({
    _i7.FileMode? mode = _i7.FileMode.read,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#open, [], {#mode: mode}),
            returnValue: _i6.Future<_i7.RandomAccessFile>.value(
              _FakeRandomAccessFile_21(
                this,
                Invocation.method(#open, [], {#mode: mode}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.RandomAccessFile>.value(
              _FakeRandomAccessFile_21(
                this,
                Invocation.method(#open, [], {#mode: mode}),
              ),
            ),
          )
          as _i6.Future<_i7.RandomAccessFile>);

  @override
  _i7.RandomAccessFile openSync({_i7.FileMode? mode = _i7.FileMode.read}) =>
      (super.noSuchMethod(
            Invocation.method(#openSync, [], {#mode: mode}),
            returnValue: _FakeRandomAccessFile_21(
              this,
              Invocation.method(#openSync, [], {#mode: mode}),
            ),
            returnValueForMissingStub: _FakeRandomAccessFile_21(
              this,
              Invocation.method(#openSync, [], {#mode: mode}),
            ),
          )
          as _i7.RandomAccessFile);

  @override
  _i6.Stream<List<int>> openRead([int? start, int? end]) =>
      (super.noSuchMethod(
            Invocation.method(#openRead, [start, end]),
            returnValue: _i6.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i6.Stream<List<int>>.empty(),
          )
          as _i6.Stream<List<int>>);

  @override
  _i7.IOSink openWrite({
    _i7.FileMode? mode = _i7.FileMode.write,
    _i11.Encoding? encoding = const _i11.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#openWrite, [], {
              #mode: mode,
              #encoding: encoding,
            }),
            returnValue: _FakeIOSink_22(
              this,
              Invocation.method(#openWrite, [], {
                #mode: mode,
                #encoding: encoding,
              }),
            ),
            returnValueForMissingStub: _FakeIOSink_22(
              this,
              Invocation.method(#openWrite, [], {
                #mode: mode,
                #encoding: encoding,
              }),
            ),
          )
          as _i7.IOSink);

  @override
  _i6.Future<_i10.Uint8List> readAsBytes() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytes, []),
            returnValue: _i6.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
            returnValueForMissingStub: _i6.Future<_i10.Uint8List>.value(
              _i10.Uint8List(0),
            ),
          )
          as _i6.Future<_i10.Uint8List>);

  @override
  _i10.Uint8List readAsBytesSync() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytesSync, []),
            returnValue: _i10.Uint8List(0),
            returnValueForMissingStub: _i10.Uint8List(0),
          )
          as _i10.Uint8List);

  @override
  _i6.Future<String> readAsString({
    _i11.Encoding? encoding = const _i11.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsString, [], {#encoding: encoding}),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  String readAsStringSync({_i11.Encoding? encoding = const _i11.Utf8Codec()}) =>
      (super.noSuchMethod(
            Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            ),
          )
          as String);

  @override
  _i6.Future<List<String>> readAsLines({
    _i11.Encoding? encoding = const _i11.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLines, [], {#encoding: encoding}),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  List<String> readAsLinesSync({
    _i11.Encoding? encoding = const _i11.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLinesSync, [], {#encoding: encoding}),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i6.Future<_i7.File> writeAsBytes(
    List<int>? bytes, {
    _i7.FileMode? mode = _i7.FileMode.write,
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsBytes,
              [bytes],
              {#mode: mode, #flush: flush},
            ),
            returnValue: _i6.Future<_i7.File>.value(
              _FakeFile_16(
                this,
                Invocation.method(
                  #writeAsBytes,
                  [bytes],
                  {#mode: mode, #flush: flush},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.File>.value(
              _FakeFile_16(
                this,
                Invocation.method(
                  #writeAsBytes,
                  [bytes],
                  {#mode: mode, #flush: flush},
                ),
              ),
            ),
          )
          as _i6.Future<_i7.File>);

  @override
  void writeAsBytesSync(
    List<int>? bytes, {
    _i7.FileMode? mode = _i7.FileMode.write,
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(#writeAsBytesSync, [bytes], {#mode: mode, #flush: flush}),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i7.File> writeAsString(
    String? contents, {
    _i7.FileMode? mode = _i7.FileMode.write,
    _i11.Encoding? encoding = const _i11.Utf8Codec(),
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsString,
              [contents],
              {#mode: mode, #encoding: encoding, #flush: flush},
            ),
            returnValue: _i6.Future<_i7.File>.value(
              _FakeFile_16(
                this,
                Invocation.method(
                  #writeAsString,
                  [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i7.File>.value(
              _FakeFile_16(
                this,
                Invocation.method(
                  #writeAsString,
                  [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush},
                ),
              ),
            ),
          )
          as _i6.Future<_i7.File>);

  @override
  void writeAsStringSync(
    String? contents, {
    _i7.FileMode? mode = _i7.FileMode.write,
    _i11.Encoding? encoding = const _i11.Utf8Codec(),
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeAsStringSync,
      [contents],
      {#mode: mode, #encoding: encoding, #flush: flush},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> exists() =>
      (super.noSuchMethod(
            Invocation.method(#exists, []),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  bool existsSync() =>
      (super.noSuchMethod(
            Invocation.method(#existsSync, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<String> resolveSymbolicLinks() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinks, []),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  String resolveSymbolicLinksSync() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinksSync, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
          )
          as String);

  @override
  _i6.Future<_i7.FileStat> stat() =>
      (super.noSuchMethod(
            Invocation.method(#stat, []),
            returnValue: _i6.Future<_i7.FileStat>.value(
              _FakeFileStat_23(this, Invocation.method(#stat, [])),
            ),
            returnValueForMissingStub: _i6.Future<_i7.FileStat>.value(
              _FakeFileStat_23(this, Invocation.method(#stat, [])),
            ),
          )
          as _i6.Future<_i7.FileStat>);

  @override
  _i7.FileStat statSync() =>
      (super.noSuchMethod(
            Invocation.method(#statSync, []),
            returnValue: _FakeFileStat_23(
              this,
              Invocation.method(#statSync, []),
            ),
            returnValueForMissingStub: _FakeFileStat_23(
              this,
              Invocation.method(#statSync, []),
            ),
          )
          as _i7.FileStat);

  @override
  _i6.Stream<_i7.FileSystemEvent> watch({
    int? events = 15,
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [], {
              #events: events,
              #recursive: recursive,
            }),
            returnValue: _i6.Stream<_i7.FileSystemEvent>.empty(),
            returnValueForMissingStub: _i6.Stream<_i7.FileSystemEvent>.empty(),
          )
          as _i6.Stream<_i7.FileSystemEvent>);
}
