// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Added for testing - returns iOS options directly
  static FirebaseOptions getIOSOptions() {
    return ios;
  }

  // Added for testing - returns Android options directly
  static FirebaseOptions getAndroidOptions() {
    return android;
  }

  // Added for testing - returns macOS options directly
  static FirebaseOptions getMacOSOptions() {
    return macos;
  }

  // Added for testing - returns Windows options directly
  static FirebaseOptions getWindowsOptions() {
    return windows;
  }

  // Added for testing - throws Linux error directly
  static void throwLinuxError() {
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
    );
  }

  // Added for testing - throws default error directly
  static void throwDefaultError() {
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }


  );
}
